[tool.taskipy.tasks]
convert-csv = { cmd = "python scripts/convert_csv.py", help = "Converte arquivos Excel em csv." }
datapackage-yaml = { cmd = "python scripts/create_datapackage_yaml.py", help = "Cria datapackage.yaml caso este ainda nÃ£o exista." }
datapackage-json = { cmd = "frictionless describe datapackage.yaml --type package --json > datapackage.json", help = "Converte datapackage.yaml em datapackage.json." }
